SmallBiz/config/routes.rb
Rails.application.routes.draw do
  get '/match', to: "match#index", :via => 'get'

  get 'match/index'

  get 'match/search'

  get 'match/list'

  get 'match/result'

  get 'landingpage/index'

  get 'resources/index'
  
  get 'resources', to: 'resources#index'
  
  get 'landingpage', to: 'landingpage#index'
  
  resources :match

  root 'landingpage#index'

end

SmallBiz/app/models/country.rb
class Country < ActiveRecord::Base
end

SmallBiz/app/models/dataset.rb
class Dataset < ActiveRecord::Base
end

SmallBiz/app/models/rec_place.rb
class RecPlace < ActiveRecord::Base
end

SmallBiz/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

SmallBiz/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController


	def new
	
	end
	
	def create
		render plain: params[:article].inspect
	end
end

SmallBiz/app/controllers/landingpage_controller.rb
class LandingpageController < ApplicationController
  def index
  end
end

SmallBiz/app/controllers/match_controller.rb
class MatchController < ApplicationController
  def index
  end

  def search
  end

  def list
  end

  def result
  end
  
  def create
      rankings = Hash.new{|key,values| values}
		i = 1
		#pull info of rank_g ie. rank greater than 6
		# query the RecPlaces table 
		finAid = params[:finanass]
		ageTarget = params[:match][:age]
		ageImportance = params[:age]
		
		regionPref = params[:region]
		incomeTarget = params[:match][:income]
		incomeImportance = params[:income]
		
		#TODO: pulling info about retail importance 
		maxFinAmount = Dataset.maximum("finamount")
		ageGroupMaxPct = Dataset.maximum(ageTarget)
		incomeMaxTarget = Dataset.maximum(incomeTarget)
		
		retailType = params[:match][:retailtype]
		indusType = params[:match][:indus]
		
			t1 = Dataset.all
			t1.each do |query|
				if(((regionPref == "Eastern Canada") && (query.Region == "Atlantic" || query.Region == "Quebec" || query.Region == "Ontario")) || (regionPref =="It doesn't matter") || ((regionPref == "Western Canada") &&  (query.Region == "Praries" || query.Region == "British Columbia")))
					#some rating based off params
					score = 0
					score += ((85*query.FinAmount) / maxFinAmount* finAid.to_i) # some scaling constant? or add some constant?
					#x1 = query.find(:select => ageTarget)
					
					score +=  ((85*query.send(ageTarget.to_sym)) / ageGroupMaxPct)*ageImportance.to_i
					score += ((85*query.send(incomeTarget.to_sym)) / incomeMaxTarget)*incomeImportance.to_i
					if(retailType != "na")
						retMax = Dataset.maximum(retailType)
						score += ((85*query.send(retailType.to_sym)) / retMax)*params[:retailType].to_i
					end
					
					if(indusType != "na")
						indMax = Dataset.maximum(indusType)
						score += ((85*query.send(indusType.to_sym)) / indMax)*params[:indus].to_i
					end
					rankings[i] = score
					
				end
				i = i + 1
			end
		#rankings.sort_by {|key,values| values}
		#@querys = rankings.values.sort.reverse.first(7)
		@matches = rankings.sort_by{|k,v| v}.reverse.first(5)
		
	
		
		
  end
  
end

SmallBiz/app/controllers/querys_controller.rb
class QuerysController < ApplicationController
	
	
	def index
		@querys = RecPlace.all
	end
	
	
	def new
	
	end

	def create
		rankings = Hash.new{|key,values| values}
		i = 1
		#pull info of rank_g ie. rank greater than 6
		# query the RecPlaces table 
		ord = params[:rank]
		if ord == 'rank_g'
			ord = 6
		elsif
			ord = 2
		end
		
		#present a view 
		t1 = RecPlace.all
			t1.each do |query|
			#some rating based off params
			score = query.rating
			rankings[i] = score
			i = i + 1
			end
		#rankings.sort_by {|key,values| values}
		#@querys = rankings.values.sort.reverse.first(7)
		@querys = rankings.sort_by{|k,v| v}.reverse.first(7)
	end
end

SmallBiz/app/controllers/resources_controller.rb
class ResourcesController < ApplicationController
end

SmallBiz/app/helpers/application_helper.rb
module ApplicationHelper
end

SmallBiz/app/helpers/articles_helper.rb
module ArticlesHelper
end

SmallBiz/app/helpers/landingpage_helper.rb
module LandingpageHelper
end

SmallBiz/app/helpers/match_helper.rb
module MatchHelper
end

SmallBiz/app/helpers/querys_helper.rb
module QuerysHelper
end

SmallBiz/app/helpers/resources_helper.rb
module ResourcesHelper
end

SmallBiz/app/views/articles/new.html.erb
<h1> New Article</h1>


<%= form_for :article, url: articles_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

SmallBiz/app/views/landingpage/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>BizMap - Canadian Business Matcher</title>

    <!-- for FF, Chrome, Opera -->
    <link rel="icon" type="image/png" href="../assets/images/icon16.png" sizes="16x16"/>
    <link rel="icon" type="image/png" href="../assets/images/icon32.png" sizes="32x32"/>

    <!-- for IE -->
    <link rel="icon" type="image/x-icon" href="../assets/images/favicon.ico" />
    <link rel="shortcut icon" type="image/x-icon" href="../assets/images/favicon.ico"/>



    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<!-- The #page-top ID is part of the scrolling feature - the data-spy and data-target are part of the built-in Bootstrap scrollspy function -->

<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top" style="font-family: GothamPro">


    <!-- Intro Section -->
    <section id="intro" class="intro-section" >
        <div class="header-shadow">
            <div class="row2">
                <a class="navbar-brand page-scroll" href="../landingpage"><img src="../assets/images/logod2.gif"/></a>
            </div>
        </div>
    </section>

    <div class="header-shadow2">
        <ul class="nav nav-tabs">
            <li role="presentation" class="active"><a href="#"><font color="#6b6c6a">Home</font></a></li>
            <li role="presentation"><a href="../match">Match</a></li>
            <li role="presentation"><a href="../resources">Resources</a></li>
        </ul>
    </div>

    <div class="jumbotron">
        <p style="font-weight: 300"><font size = 30 color="6c6d6a">Welcome to <font color="e05c5e">BizMap!</font></font></p>
        <div style="height:40px"></div>
        <p><a class="btn btn-custom" href="../match" role="button"><font size="5" style="font-weight: 100">Find Your Match</font></a></p>
    </div>

    <!-- About Section -->
    <section id="about" class="about-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-12" align="center">
                    <div style="height:20px;"></div>
                    <div style="font-weight: 100"><font color="#FFFFFF" size=30>About </font><font color="e05c5e" size=30>BizMap</font></h1></div>
                    <div style="height:30px;"></div>
                    <div style="font-weight: 100"><font color="#FFFFFF" size=5>We present BizMap, a tool for Canadians looking to start their own small businesses in Canada. Using <font color="e05c5e">Canadian Open data sets</font>, we will determine the best city to start your business based on the local economy, demographic, and operation costs.</font></div>
                </div>
            </div>
        </div>
    </section>

    <div class="middle_banner">
        <div style="height:150px;"></div>
    </div>

    <!-- Services Section -->
    <section id="services" class="services-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-12" align="center">
                    <div style="height:20px;"></div>
                    <div style="font-weight: 200"><font color="#6c6d6a" size=30>Meet the </font><font color="e05c5e" size=30>Team!</font></h1></div>
                    <div style="height:30px;"></div>
                    <div style="font-weight: 200"><font color="#6c6d6a" size=5>We are an academically diverse group of undergraduate students at the <font color="e05c5e">University of British Columbia</font> situated in beautiful Vancouver, Canada. We'd love to hear from you!</font></div>
                </div>
            </div>
        </div>
        <div style="height:100px;"></div>
        <!-- Team Members Row -->
        <div class="container">
        <div class="row">
            <div class="col-lg-6 col-sm-6 text-center">
                <img src="../assets/images/erica.png" align="center">
                <p style="font-weight: 200"><font color="6c6d6a" size=5>Erica <font color="e35d60">Lin</font></font> 
                    </br>
                    <font color="8f8f8f">Front End</font>
                </p>
                <p class="profile-text"><font color="8f8f8f">Microbiology &amp; Computer Science</br>Year 2</font></p>
            </div>
            <div class="col-lg-6 col-sm-6 text-center">
                <img src="../assets/images/michael2.png" align="center">
                <p style="font-weight: 200"><font color="6c6d6a" size=5>Michael <font color="e35d60">Yau</font></font> 
                    </br>
                    <font color="8f8f8f">Front End</font>
                </p>
                <p class="profile-text"><font color="8f8f8f">Pharmacology</br>Year 4</font></p>
            </div>
        </div>
        <div style="height:100px;"></div>
        <div class="row">
            <div class="col-lg-6 col-sm-6 text-center">
                <img src="../assets/images/austin.png" align="center">
                <p style="font-weight: 200"><font color="6c6d6a" size=5>Austin <font color="e35d60">Chen</font></font> 
                    </br>
                    <font color="8f8f8f">Back End</font>
                </p>
                <p class="profile-text"><font color="8f8f8f">Developmental Neurobiology</br>Year 4</font></p>
            </div>
            <div class="col-lg-6 col-sm-6 text-center">
                <img src="../assets/images/john.png" align="center">
                <p style="font-weight: 200"><font color="6c6d6a" size=5>John <font color="e35d60">Hsu</font></font> 
                    </br>
                    <font color="8f8f8f">Back End</font>
                </p>
                <p class="profile-text"><font color="8f8f8f">Math &amp; Economics</br>Year 4</font></p>
            </div>
        </div>
        </div>
    </section>

    <div class="bottom_banner">
        <div style="height:250px;"></div>
    </div>

    <!-- Contact Section -->
    <section id="contact" class="contact-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-12" align="center">
                    <div style="height:20px;"></div>
                    <div style="font-weight: 100"><font color="e05c5e" size=30>Contact </font><font color="#FFFFFF" size=30>Us</font></h1></div>
                    <div style="height:30px;"></div>
                    <div style="font-weight: 100"><font color="#FFFFFF" size=5>Got any questions or comments? Drop us a message!</font>
                        </br></br>
                        <p style="font-weight: 150px00"><font color="#FFFFFF">Team Hortons UBC</br>contact.teamhortons@gmail.com</font></p>
                        </br></br></br>
                        <img src="../assets/images/teamhortons.gif">
                    </div>
                </div>
            </div>
        </div>
    </section>



<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
<script type="text/javascript" src="http://arrow.scrolltotop.com/arrow88.js"></script>
<noscript>Not seeing a <a href="http://www.scrolltotop.com/">Scroll to Top Button</a>? Go to our FAQ page for more info.</noscript>

</body>

</html>

SmallBiz/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= yield :title %>

    <!-- Bootstrap Core CSS -->
    <link href="/assets/bootstrap
    .css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="assets/scrolling-nav.css" rel="stylesheet">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

    <!-- jQuery -->
    <script src="assets/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="assets/bootstrap.min.js"></script>

    <!-- Scrolling Nav JavaScript -->
    <script src="assets/jquery.easing.min.js"></script>
    <script src="assets/scrolling-nav.js"></script>
    
</body>
</html>

SmallBiz/app/views/match/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Find Your Match</title>



    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<!-- The #page-top ID is part of the scrolling feature - the data-spy and data-target are part of the built-in Bootstrap scrollspy function -->

<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top" style="font-family: GothamPro">
<font color="6c6d6a">
 <!-- Intro Section -->
    <section id="intro" class="intro-section" >
        <div class="header-shadow">
            <div class="row2">
                <a class="navbar-brand page-scroll" href="../landingpage"><img src="../assets/images/logod2.gif"/></a>
            </div>
        </div>
    </section>

    <div class="header-shadow2">
        <ul class="nav nav-tabs">
            <li role="presentation"><a href="../landingpage">Home</a></li>
            <li role="presentation" class="active"><a href="#">Match</a></li>
            <li role="presentation"><a href="../resources">Resources</a></li>
        </ul>
    </div>

<!-- Resources Section -->
    <section id="resources" class="resources-section">
        <div class="container" style="font-weight: 200">
            <p><font size=10>Let's Find <font color="e35d60">Your City!</font></font></p><br>

<%= form_for :match, url: match_path do |f| %>
<div class="matchbg" style="font-weight: 200; font-size: 25px">
    <p>
        <font color="e35d60"><%= f.label :region, ""%></font><br>
        <font size=4>Where in Canada would you like to start your business?</font><br>
        <%=radio_button_tag(:region, "Western Canada", 'on')%><font size=4> Western Canada</font>
        <%=label_tag(:region_1,"") %>
        <%=radio_button_tag(:region, "Eastern Canada")%><font size=4> Eastern Canada</font>
        <%=label_tag(:region_2,"")%>
        <%=radio_button_tag(:region, "It doesn't matter")%><font size=4> It doesn't matter</font>
        <%=label_tag(:region_3,"")%>
    </p>
    <p>
        <font color="e35d60"><%= f.label :finanass, "Financial Assistance" %></font><br>
        <font size=4>To you, how important is the availability of financial aid?</font><br>
        <%= radio_button_tag(:finanass, "1", 'on') %>
        <%= label_tag(:finanass_1, "") %><img src="../assets/images/mapleleaf.gif">
        <%= radio_button_tag(:finanass, "2") %>
        <%= label_tag(:finanass_2, "") %><img src="../assets/images/mapleleaf.gif"><img src="../assets/images/mapleleaf.gif">
        <%= radio_button_tag(:finanass, "3") %>
        <%= label_tag(:finanass_3, "") %><img src="../assets/images/mapleleaf.gif"><img src="../assets/images/mapleleaf.gif"><img src="../assets/images/mapleleaf.gif">
    </p>

    <p>
        <font color="e35d60"><%= f.label :age, "Targeted Age Groups" %></font><br>
        <font size=4>
        <%= f.select( :age, options_for_select([["Choose one:", "PctPerson024"], ["0 to 24", "PctPerson024"], ["25 to 44", "PctPerson2544"], ["45 to 64", "PctPerson4564"], ["65 and older", "PctPerson65Over"]])) %>
        </font><br>
        <font size=4>To you, how important is the targeted age group?</font><br>
        <%= radio_button_tag(:age, "1", 'on') %>
        <%= label_tag(:age_1, "") %><img src="../assets/images/mapleleaf.gif">
        <%= radio_button_tag(:age, "2") %>
        <%= label_tag(:age_2, "") %><img src="../assets/images/mapleleaf.gif"><img src="../assets/images/mapleleaf.gif">
        <%= radio_button_tag(:age, "3") %>
        <%= label_tag(:age_3, "") %><img src="../assets/images/mapleleaf.gif"><img src="../assets/images/mapleleaf.gif"><img src="../assets/images/mapleleaf.gif">
    </p>

    <p>
        <font color="e35d60"><%= f.label :income, "Targeted Income Groups" %></font><br>
        <font size=4>
        <%= f.select( :income, options_for_select([["Choose one:", "PctOver15K"], ["$15,000 and greater", "PctOver15K"], ["$50,000 and greater", "PctOver50K"], ["$100,000 and greater", "PctOver100K"]])) %>
        </font><br>
        <font size=4>To you, how important is the targeted income group?</font><br>
        <%= radio_button_tag(:income, "1", 'on') %>
        <%= label_tag(:income_1, "") %><img src="../assets/images/mapleleaf.gif">
        <%= radio_button_tag(:income, "2") %>
        <%= label_tag(:income_2, "") %><img src="../assets/images/mapleleaf.gif"><img src="../assets/images/mapleleaf.gif">
        <%= radio_button_tag(:income, "3") %>
        <%= label_tag(:income_3, "") %><img src="../assets/images/mapleleaf.gif"><img src="../assets/images/mapleleaf.gif"><img src="../assets/images/mapleleaf.gif">
    </p>

    <div class="alert alert-info" role="alert"><font size=4>If your business involves sales of goods, choose the most applicable retail category below. Otherwise, choose the most applicable non-retail/industry category below.</font></div>
    <p>
        <font color="e35d60"><%= f.label :retailtype, "Retail-type" %></font><br>
        <font size=4>
        <%= f.select( :retailtype, options_for_select([ ["Not Applicable", "na"],
                                                        ["Motor vehicle and parts dealers", "Motor"],
                                                        ["Furniture and home furnishings stores", "Furniture"],
                                                        ["Electronics and appliance stores", "Electronic"],
                                                        ["Building material and garden equipment and supplies dealers", "BuildingGardenMaterial"],
                                                        ["Food and beverage stores", "FoodDrink"],
                                                        ["Health and personal care stores", "HealthPersonal"],
                                                        ["Gasoline stations", "Gas"],
                                                        ["Clothing and clothing accessories stores", "Clothing"],
                                                        ["Sporting goods, hobby, book and music stores", "Sports"],
                                                        ["General merchandise stores", "General"],
                                                        ["Miscellaneous store retailers", "Miscellaneous"]])) %> <br>
        How accurate is this classification? (If applicable) <br>
        <%= radio_button_tag(:retailtype, "1", 'on') %>
        <%= label_tag(:retailtype_1, "") %><img src="../assets/images/mapleleaf.gif">
        <%= radio_button_tag(:retailtype, "2") %>
        <%= label_tag(:retailtype_2, "") %><img src="../assets/images/mapleleaf.gif"><img src="../assets/images/mapleleaf.gif">
        <%= radio_button_tag(:retailtype, "3") %>
        <%= label_tag(:retailtype_3, "") %><img src="../assets/images/mapleleaf.gif"><img src="../assets/images/mapleleaf.gif"><img src="../assets/images/mapleleaf.gif">
        </font>
    </p>

    <p>
        <font color="e35d60"><%= f.label :indus, "Non-Retail Industry-type" %></font><br>
        <font size=4>
        <%= f.select( :indus, options_for_select([      ["Not applicable", "na"],
                                                        ["Agriculture employment", "Agriculture"],
                                                        ["Forestry, fishing, mining, quarrying, oil and gas employment", "Forestry"],
                                                        ["Utilities employment", "Utilities"],
                                                        ["Construction employment", "Construction"],
                                                        ["Manufacturing employment", "Manufacturing"],
                                                        ["Trade employment", "Trade"],
                                                        ["Transportation and warehousing employment", "TransporationWarehousing"],
                                                        ["Finance, insurance, real estate and leasing employment", "FinanceInsuranceRealEstate"],
                                                        ["Professional, scientific and technical services employment", "ProfScientificTechnical"],
                                                        ["Business, building and other support services employment", "BusinessBuildingSupportService"],
                                                        ["Educational services employment", "Education"],
                                                        ["Health care and social assistance employment", "HealthCare"],
                                                        ["Information, culture and recreation employment", "InformationCultureRecreation"],
                                                        ["Accommodation and food services employment", "Accomodation"],
                                                        ["Other services employment", "OtherServices"],
                                                        ["Public administration employment", "PublicAdmin"]])) %> <br>
        How accurate is this classification? (If applicable) <br>
        <%= radio_button_tag(:indus, "1", 'on') %>
        <%= label_tag(:indus_1, "") %><img src="../assets/images/mapleleaf.gif">
        <%= radio_button_tag(:indus, "2") %>
        <%= label_tag(:indus_2, "") %><img src="../assets/images/mapleleaf.gif"><img src="../assets/images/mapleleaf.gif">
        <%= radio_button_tag(:indus, "3") %>
        <%= label_tag(:indus_3, "") %><img src="../assets/images/mapleleaf.gif"><img src="../assets/images/mapleleaf.gif"><img src="../assets/images/mapleleaf.gif">
        </font>
    </p>
    <br>
    <p>
        <%= f.submit %>
    </p>
    <br><br>

<% end %>
        </div>
    </div>
    </section>


<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
<script type="text/javascript" src="http://arrow.scrolltotop.com/arrow88.js"></script>
<noscript>Not seeing a <a href="http://www.scrolltotop.com/">Scroll to Top Button</a>? Go to our FAQ page for more info.</noscript>
</font>
</body>

</html>

SmallBiz/app/views/match/list.html.erb
<h1>Match#list</h1>
<p>Find me in app/views/match/list.html.erb</p>

SmallBiz/app/views/match/result.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>



<div style='width: 800px;'>
  <div id="multi_markers" style='width: 800px; height: 400px;'></div>
</div>

<script type="text/javascript">

var handler = Gmaps.build('Google');

var address1 = "Toronto"
$.ajax({
  url:"http://maps.googleapis.com/maps/api/geocode/json?address="+address1+"&sensor=false",
  type: "POST",
  success:function(res){
     lat1 = res.results[0].geometry.location.lat;
     lng1 = res.results[0].geometry.location.lng;
  }
});

var address2 = "Vancouver"
$.ajax({
  url:"http://maps.googleapis.com/maps/api/geocode/json?address="+address2+"&sensor=false",
  type: "POST",
  success:function(res){
     lat2 = res.results[0].geometry.location.lat;
     lng2 = res.results[0].geometry.location.lng;
  }
});

var address3 = "Calgary"
$.ajax({
  url:"http://maps.googleapis.com/maps/api/geocode/json?address="+address3+"&sensor=false",
  type: "POST",
  success:function(res){
     lat3 = res.results[0].geometry.location.lat;
     lng3 = res.results[0].geometry.location.lng;
  }
});

var address4 = "Life Science Institute"
$.ajax({
  url:"http://maps.googleapis.com/maps/api/geocode/json?address="+address4+"&sensor=false",
  type: "POST",
  success:function(res){
     lat4 = res.results[0].geometry.location.lat;
     lng4 = res.results[0].geometry.location.lng;
  }
});

var address5 = "Quebec City"
$.ajax({
  url:"http://maps.googleapis.com/maps/api/geocode/json?address="+address5+"&sensor=false",
  type: "POST",
  success:function(res){
     lat5 = res.results[0].geometry.location.lat;
     lng5 = res.results[0].geometry.location.lng;
  }
});

handler.buildMap({ internal: {id: 'multi_markers'}}, function(){
  var markers = handler.addMarkers([
    { lat: lat1, lng: lng1},
    { lat: lat2, lng: lng2},
    { lat: lat3, lng: lng3},
    { lat: lat4, lng: lng4},
    { lat: lat5, lng: lng5}
  ]);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});

</script>

SmallBiz/app/views/match/search.html.erb
<h1>Match#search</h1>
<p>Find me in app/views/match/search.html.erb</p>

SmallBiz/app/views/querys/create.html.erb
<h1>Listing Queries</h1>
<table>
  <tr>
    <th>Name</th>
    <th>Rating</th>
	<th>Age</th>
  </tr>
  
  <% @querys.each do |query| %>
  <% key = query[0] %>
  <% row = RecPlace.find(key+34)%>
    <tr>
      <td><%= row.name %></td>
      <td><%= row.rating %></td>
	  <td><%= row.age %></td>
    </tr>
 <%end%>
  

</table>

SmallBiz/app/views/querys/index.html.erb
<h1>Listing Queries</h1>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
	<th>Age</th>
  </tr>
 
  <% @querys.each do |query| %>
    <tr>
      <td><%= query.name %></td>
      <td><%= query.rating %></td>
	  <td><%= query.age %></td>
    </tr>
  <% end %>
</table>

SmallBiz/app/views/querys/new.html.erb
<h1> Queries</h1>


<%= form_for :query, url: querys_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p> How old are you? </p>
<%= radio_button_tag(:age, "child") %>
  <%= label_tag(:age_child, "I am younger than 21") %>
  <%= radio_button_tag(:age, "adult") %>
  <%= label_tag(:age_adult, "I'm over 21") %>
 
   <p>Ranking greater than 6? </p>
<%= radio_button_tag(:rank, "rank_g") %>
  <%= label_tag(:rank_g, "Yes, rank greater than 6") %>
  <%= radio_button_tag(:rank, "rank_l") %>
  <%= label_tag(:rank_l, "No, rank less than 6") %>
 
 
  <p>
    <%= f.submit %>
  </p>
<% end %>